service_account: ""
fullnameOverride: ""

miner:
  replicaCount: 1
  address: "127.0.0.1"
  port: 12340
  user_address: "127.0.0.1"
  user_port: 12360
  owner: "owner"
  period: "5-month"
  api_key: "API_KEY"
  node_name: "nodeName"
  disk_name: "diskName"
  image:
    repository: ghcr.io/barryboot/zenotta-cloud-mining
    tag: main
  limits:
    memory: 6Gi
    cpu: 1500m
  requests:
    memory: 5Gi
    cpu: 1000m
  configMap:
    RUST_LOG: "info,debug"