# DB mode
miner_db_mode = { Live = 0 }

# API Port
miner_api_port = 3000

# Will need to get replaced with a valid API key when whitelisting is activated
mining_api_key = "YOUR_API_KEY"

# Loki testnet
#address = "34.209.131.212:12300"
[[compute_nodes]]
address = "34.209.131.212:80"

# This miner node instance
[[miner_nodes]]
address = "127.0.0.1:12340"

# Used to spin up a seperate user node thread
# [[user_nodes]]
# address = "127.0.0.1:12360"

