service_account: ""
fullnameOverride: ""

miner:
  replicaCount: 1
  address: "127.0.0.1"
  port: 12340
  image:
    repository: ghcr.io/barryboot/zenotta-cloud-mining
    tag: main
  limits:
    memory: 6Gi
    cpu: 1500m
  requests:
    memory: 5Gi
    cpu: 1000m
  configMap:
    RUST_LOG: "warp"