apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ include "miner.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: zenotta-wallet