---
# Deployment for the API Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miner.fullname" . }}
  labels:
    {{- include "miner.labels" . | nindent 4 }}
spec:
  replicas: {{ (.Values.miner).replicaCount }}
  selector:
    matchLabels:
      {{- include "miner.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 6
      maxUnavailable: 2
  template:
    metadata:
      labels:
        {{- include "miner.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ .Values.service_account }}"
      containers:
        - name: {{ include "miner.fullname" . }}
          image: "{{ .Values.miner.image.repository }}:{{ .Values.miner.image.tag }}"
          resources:
            limits:
              memory: {{ .Values.miner.limits.memory }}
              cpu: {{ .Values.miner.limits.cpu }}
            requests:
              memory: {{ .Values.miner.requests.memory }}
              cpu: {{ .Values.miner.requests.cpu }}
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ include "miner.fullname" . }}-configmap
            - secretRef:
                name: {{ include "miner.fullname" . }}-secret
