---
# Deployment for the API Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miner.fullname" . }}
  labels:
    {{- include "miner.labels" . | nindent 4 }}
spec:
  replicas: {{ (.Values.miner).replicaCount }}
  selector:
    matchLabels:
      {{- include "miner.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 6
      maxUnavailable: 2
  template:
    metadata:
      labels:
        {{- include "miner.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ .Values.service_account }}"
      containers:
        - name: {{ include "miner.fullname" . }}
          image: "{{ (.Values.miner).image.repository }}:{{ .Values.miner.image.tag }}"
          command: 
            - "/zenotta/target/release/node"
            - "miner"
            - "--config=/etc/node_settings.toml"
            - "--tls_config=/etc/tls_certificates.json"
            - "--initial_block_config=/etc/initial_block.json"
            - "--api_config=/etc/api_config.json"
            - "--api_use_tls=0"
            - "--with_user_address={{ (.Values.miner).user_address }}:{{ (.Values.miner).user_port }}"
            - "--address={{ (.Values.miner).address }}:{{ (.Values.miner).port }}"
          resources:
            limits:
              memory: {{ (.Values.miner).limits.memory }}
              cpu: {{ (.Values.miner).limits.cpu }}
              nvidia.com/gpu: 1
            requests:
              memory: {{ (.Values.miner).requests.memory }}
              cpu: {{ (.Values.miner).requests.cpu }}
              nvidia.com/gpu: 1
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ include "miner.fullname" . }}-configmap
            - secretRef:
                name: {{ include "miner.fullname" . }}-secret
